apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-deployment
  labels:
    app: element
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element
  template:
    metadata:
      labels:
        app: element
    spec:
      containers:
        - name: element
          image: vectorim/riot-web
          ports:
            - containerPort: 80
